"""add repository analysis metadata

Revision ID: 58a7add677de
Revises: b71ea208accb
Create Date: 2026-09-03 10:22:07.252960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a7add677de'
down_revision: Union[str, Sequence[str], None] = 'b71ea208accb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('local_path', sa.Text(), nullable=True))
    op.add_column('repositories', sa.Column('file_count', sa.Integer(), nullable=False, server_default=sa.text("0"),),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'file_count')
    op.drop_column('repositories', 'local_path')
    # ### end Alembic commands ###
